name: Docker CD

on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - name: checkout code
        uses: actions/checkout@v2
    
#       - name: Log in to ghcr
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Set tag if master
        if: github.event.action == 'branches'
        run: echo "TAG=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
        
      - name: Set tag if tag
        if: github.event.action == 'tags'
        run: echo "TAG=$(git describe --tags)" >> $GITHUB_ENV
    
      - name: TEST
        run: echo ${{ github.event.action }}
    
#       - name: Build & Push
#         uses: docker/build-push-action@v2
#         with:
#           context: ./build
#           file: ./build/Dockerfile
#           push: true
#           tags: ghcr.io/filipw/dotnet-script:latest
